services:
  - type: web
    name: api-doacao-livros
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production